env:
  IMAGE_NAME: ots-image
  ID_PROJECT: terraform-project-atserge1
  PROJECT_REPO: ots-project-repo
  KUBE_CONFIG: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhvcml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VWTVJFTkRRWEJUWjBGM1NVSkJaMGxSUVZsb2RrcEhORFE0ZVZCTlZIRjRVRXRNWTI1TWFrRk9RbWRyY1docmFVYzVkekJDUVZGelJrRkVRWFlLVFZNd2QwdDNXVVJXVVZGRVJYbFJNazE2Um1sYVZFWm9UMU14YTAweVRtMU1WRkUxVFhwamRFOVVTbXRPVXpGc1drUkZNbGw2VFhsT2FteHNXa2ROZHdwSlFtTk9UV3BOZDAxNlRYZE5SRWt4VGtSRk0xZG9aMUJOYWtFeFRYcEJlazFxU1hkTmVsVXdUVlJrWVUxRE9IaE1WRUZ5UW1kT1ZrSkJUVlJLUkZsNkNrMVhTbXhOVjBVMVRGZFJlbGt5V1hST1JHdDZUbmt3TlUxdFVURk1WMVpyVFZSYWFrMTZTVEpQVjFacldYcERRMEZoU1hkRVVWbEtTMjlhU1doMlkwNEtRVkZGUWtKUlFVUm5aMGRRUVVSRFEwRlpiME5uWjBkQ1FVMVpZMnRJTmxWTFVETTFjREJNYVhSa1RqbEdlSGxaUzNSUFZ6bEZiRGhhSzB0NFF6ZENUd3B3VmpaWGJYQXZXRXBEUVhGa1RtTlFhMVZUYzBWbWIzbG1iVUYwUW1ocVNrWlJlbkZNVGtReGNGcEVZMFJ6VUVWaldtTnZXRmRPTW5CQlRrRkRXbGc0Q2xoSWRHSlZSRmxVY1hwMWNHZzVRamhCVFhjMVVrd3hXakpRZFdWNFJWSjZMek5VV1hKcWJYTkpkbTVvTjFSVk4yVkhkRkptV0RGeU5HRkhURGRLTWxBS1UxVXJiVTFOTkdveGFXcFVWRmR1YmxBM2VWbGFRMDVGY0VsTGExVTNNRGhMWTBsME9XeEJWM2t5U0ZCWmEwSTJZelUzYUd4SGNrbGlOMGRLY0RCS09RcE5PWGhyYTBsQ056SjZTMWx1VG5KNVZsbDRibGxZYXl0Qk15dHFWa3R3ZVZKRmQxQnRXbkJxVkM5VmVFSndVMmMzY0haRVZuRlViRTFpY1VKMmJqbHVDbTFXTkVkbFRXVklMMGxDWkU1dldYWkljVWhYWkZoR05ERXlUbkZSYW1vMlZXdFllalpwV0RnMFZsZzRSaXN4ZEZoTmFEWTJOVGxIYnpCTVdEQkdWbGdLVVZCc1dYbERORFpLZFhaemFUbFRMMjFSVkdSMFJERlFkamRtVWpoaFkwRnFjWEJ2VDFBM1lXNTNRbkp4U2swMlJXRnJNa05ST1hoVVVHdGlObEZtUlFvNVlWQTVXVGd4WW5Jd1ptaGhMMWxNTDBGdE1HcDBaRk5CS3pONVdWaFNNVTV5UnlzdkszbFdOVEpaTjBnMGRHNXBiM1poVGtsV2IzQkllV3d3T0ZJM0NraHVZMjE2VFRKaFpEaDRkMnBEVXpkblRuSlBRMDlQVEVOUlNVUkJVVUZDYnpCSmQxRkVRVTlDWjA1V1NGRTRRa0ZtT0VWQ1FVMURRV2RSZDBSM1dVUUtWbEl3VkVGUlNDOUNRVlYzUVhkRlFpOTZRV1JDWjA1V1NGRTBSVVpuVVZWT1FUUlZSMEZSVUZKelpUWlhlRWQzVGtwUVdsbFlNbU12U2xWM1JGRlpTZ3BMYjFwSmFIWmpUa0ZSUlV4Q1VVRkVaMmRIUWtGQ2MySjRjM0oxUlRCTFluRTJOalJVZUhCUWMxcEdialZTZFU1aFREZFNhamxPU21jdlNGWlhSRzExQ2s1ekswTXljek15V1U5SlNsaEdibXRUYURsVEwzUldVV1pVVkZKb1RqVmxOblExY2pBNU1EZG1ibTFGT1N0cGFUQm9PRFJUU2xWRFQzTk9iMWx4TDAwS1RGaHZiekkzUTJSUFprdHRZVFZGTkZGSWFtdHNZakpYVWs4eVJuVlVZM1VyVDNvd2NGQlNVMEZtU1RCT1luVjRTM0ZHTWpGQ05TOW5RV2xtVmtSWlRncFBNekZ0U2pKdllVdHNPV3gyZURaQ2JUVXZXV1owSzBKemFFMWFVRTFMWldOVFlqbFZUbVpOWTNKcmIzbFVWSFo1WmpjeVIzSnNTbmNyZVhsMFdVbDFDbXcyYW01WlZHOVpaVU5vT0RSblFXeEpaR1Z4VUdnd1pIWTRlbmxpWlZKUGFrbDZOVEpsYkRGRU9EVndkazVPWTFKemVHZEdWWElyUXpoUmNGTXdaRklLTTJzMFYwVjJaWFZaT0ZwWWEwNURXWFY2TTB0Rk5rUTNZVlJTVjFBNFduRlNNM1UxYW1KMVNtOXdWRmRNV1VwVVFWTTFhMlpDTVZkb2RuY3ZNelJWY1Fwc1NYSXJWSFJDWkRrMVdXVnVRMmh5ZVVwQmFVcG9NVEJzZEVSd1pFVkdiRE50WXpGSWNubGFSaTh2UW1GbFZIVXZRVXN5Wkd4a1JqWlVUREZuY1hwV0NsVk1MMU5XU0VGMGNrVjBXV0ZLSzNCTE4zbGhTRXRFWkhBeVNUVnBOaXRTY0VFMVFuRklZVmhvVGxkdE1VdDBMMVZQYVRSWFlsSmtXRVY0YURsWE5uUUtZMHBGWjJaWWIxZDRlVWR3ZEZabU1VSnBWV0prWnowOUNpMHRMUzB0UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwSwogICAgc2VydmVyOiBodHRwczovLzM0LjI3LjE0Ny45MgogIG5hbWU6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9wcm9qZWN0LWNsdXN0ZXIKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9wcm9qZWN0LWNsdXN0ZXIKICAgIHVzZXI6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9wcm9qZWN0LWNsdXN0ZXIKICBuYW1lOiBna2VfdGVycmFmb3JtLXByb2plY3QtYXRzZXJnZTFfdXMtY2VudHJhbDFfcHJvamVjdC1jbHVzdGVyCmN1cnJlbnQtY29udGV4dDogZ2tlX3RlcnJhZm9ybS1wcm9qZWN0LWF0c2VyZ2UxX3VzLWNlbnRyYWwxX3Byb2plY3QtY2x1c3RlcgpraW5kOiBDb25maWcKcHJlZmVyZW5jZXM6IHt9CnVzZXJzOgotIG5hbWU6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9wcm9qZWN0LWNsdXN0ZXIKICB1c2VyOgogICAgZXhlYzoKICAgICAgYXBpVmVyc2lvbjogY2xpZW50LmF1dGhlbnRpY2F0aW9uLms4cy5pby92MWJldGExCiAgICAgIGNvbW1hbmQ6IGdrZS1nY2xvdWQtYXV0aC1wbHVnaW4KICAgICAgaW5zdGFsbEhpbnQ6IEluc3RhbGwgZ2tlLWdjbG91ZC1hdXRoLXBsdWdpbiBmb3IgdXNlIHdpdGgga3ViZWN0bCBieSBmb2xsb3dpbmcKICAgICAgICBodHRwczovL2Nsb3VkLmdvb2dsZS5jb20vYmxvZy9wcm9kdWN0cy9jb250YWluZXJzLWt1YmVybmV0ZXMva3ViZWN0bC1hdXRoLWNoYW5nZXMtaW4tZ2tlCiAgICAgIHByb3ZpZGVDbHVzdGVySW5mbzogdHJ1ZQo=

name: Deployment
on:
  push:
    branches: [atserge1]
  workflow_dispatch:
jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.ATSERGE_SA_KEY }}
          project_id: ${{ env.ID_PROJECT }}
          export_default_credentials: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
      
      - name: Debug secrets 
        run: |
          echo "HELLO" | base64
          echo ${{ secrets.KUBE_CONFIG }} 
          echo "${{ secrets }}"


      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'project-cluster'
          location: 'us-central1'

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - id: 'kubeconfig'
        run: 'mkdir ~/.kube && cat $KUBECONFIG > ~/.kube/config'    
                
      - name: Terraform init
        working-directory: deployment
        run: |
          terraform init
          
      
      - name: Terraform apply
        working-directory: deployment
        run: |
          terraform apply -auto-approve
