env:
  IMAGE_NAME: ots-image
  ID_PROJECT: terraform-project-atserge1
  PROJECT_REPO: ots-project-repo

name: Deployment
on:
  push:
    branches: [atserge1]
  workflow_dispatch:
jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.ATSERGE_SA_KEY }}
          project_id: ${{ secrets.ID_PROJECT }}
          export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
      
      # - name: Debug secrets context
      #   run: |
      #     echo "Hello"
      #    echo ${{ secrets.KUBECONFIG }} 
      #     echo "${{ secrets }}"

      - id: 'kubeconfig'
        run: 'mkdir ~/.kube && cat $KUBECONFIG > ~/.kube/config'
      
      - name: Terraform init
        run: |
          cd deployment
          terraform init
      - name: Terraform apply
        run: |
          cd deployment
          terraform apply -auto-approve -input=false