env:
  IMAGE_NAME: ots-image
  ID_PROJECT: terraform-project-atserge1
  PROJECT_REPO: ots-project-repo
  KUBE_CONFIG: YXBpVmVyc2lvbjogdjEKY2x1c3RlcnM6Ci0gY2x1c3RlcjoKICAgIGNlcnRpZmljYXRlLWF1dGhv
cml0eS1kYXRhOiBMUzB0TFMxQ1JVZEpUaUJEUlZKVVNVWkpRMEZVUlMwdExTMHRDazFKU1VWTVJF
TkRRWEJUWjBGM1NVSkJaMGxSUVZsb2RrcEhORFE0ZVZCTlZIRjRVRXRNWTI1TWFrRk9RbWRyY1do
cmFVYzVkekJDUVZGelJrRkVRWFlLVFZNd2QwdDNXVVJXVVZGRVJYbFJNazE2Um1sYVZFWm9UMU14
YTAweVRtMU1WRkUxVFhwamRFOVVTbXRPVXpGc1drUkZNbGw2VFhsT2FteHNXa2ROZHdwSlFtTk9U
V3BOZDAxNlRYZE5SRWt4VGtSRk0xZG9aMUJOYWtFeFRYcEJlazFxU1hkTmVsVXdUVlJrWVUxRE9I
aE1WRUZ5UW1kT1ZrSkJUVlJLUkZsNkNrMVhTbXhOVjBVMVRGZFJlbGt5V1hST1JHdDZUbmt3TlUx
dFVURk1WMVpyVFZSYWFrMTZTVEpQVjFacldYcERRMEZoU1hkRVVWbEtTMjlhU1doMlkwNEtRVkZG
UWtKUlFVUm5aMGRRUVVSRFEwRlpiME5uWjBkQ1FVMVpZMnRJTmxWTFVETTFjREJNYVhSa1RqbEdl
SGxaUzNSUFZ6bEZiRGhhSzB0NFF6ZENUd3B3VmpaWGJYQXZXRXBEUVhGa1RtTlFhMVZUYzBWbWIz
bG1iVUYwUW1ocVNrWlJlbkZNVGtReGNGcEVZMFJ6VUVWaldtTnZXRmRPTW5CQlRrRkRXbGc0Q2xo
SWRHSlZSRmxVY1hwMWNHZzVRamhCVFhjMVVrd3hXakpRZFdWNFJWSjZMek5VV1hKcWJYTkpkbTVv
TjFSVk4yVkhkRkptV0RGeU5HRkhURGRLTWxBS1UxVXJiVTFOTkdveGFXcFVWRmR1YmxBM2VWbGFR
MDVGY0VsTGExVTNNRGhMWTBsME9XeEJWM2t5U0ZCWmEwSTJZelUzYUd4SGNrbGlOMGRLY0RCS09R
cE5PWGhyYTBsQ056SjZTMWx1VG5KNVZsbDRibGxZYXl0Qk15dHFWa3R3ZVZKRmQxQnRXbkJxVkM5
VmVFSndVMmMzY0haRVZuRlViRTFpY1VKMmJqbHVDbTFXTkVkbFRXVklMMGxDWkU1dldYWkljVWhY
WkZoR05ERXlUbkZSYW1vMlZXdFllalpwV0RnMFZsZzRSaXN4ZEZoTmFEWTJOVGxIYnpCTVdEQkdW
bGdLVVZCc1dYbERORFpLZFhaemFUbFRMMjFSVkdSMFJERlFkamRtVWpoaFkwRnFjWEJ2VDFBM1lX
NTNRbkp4U2swMlJXRnJNa05ST1hoVVVHdGlObEZtUlFvNVlWQTVXVGd4WW5Jd1ptaGhMMWxNTDBG
dE1HcDBaRk5CS3pONVdWaFNNVTV5UnlzdkszbFdOVEpaTjBnMGRHNXBiM1poVGtsV2IzQkllV3d3
T0ZJM0NraHVZMjE2VFRKaFpEaDRkMnBEVXpkblRuSlBRMDlQVEVOUlNVUkJVVUZDYnpCSmQxRkVR
VTlDWjA1V1NGRTRRa0ZtT0VWQ1FVMURRV2RSZDBSM1dVUUtWbEl3VkVGUlNDOUNRVlYzUVhkRlFp
OTZRV1JDWjA1V1NGRTBSVVpuVVZWT1FUUlZSMEZSVUZKelpUWlhlRWQzVGtwUVdsbFlNbU12U2xW
M1JGRlpTZ3BMYjFwSmFIWmpUa0ZSUlV4Q1VVRkVaMmRIUWtGQ2MySjRjM0oxUlRCTFluRTJOalJV
ZUhCUWMxcEdialZTZFU1aFREZFNhamxPU21jdlNGWlhSRzExQ2s1ekswTXljek15V1U5SlNsaEdi
bXRUYURsVEwzUldVV1pVVkZKb1RqVmxOblExY2pBNU1EZG1ibTFGT1N0cGFUQm9PRFJUU2xWRFQz
Tk9iMWx4TDAwS1RGaHZiekkzUTJSUFprdHRZVFZGTkZGSWFtdHNZakpYVWs4eVJuVlVZM1VyVDNv
d2NGQlNVMEZtU1RCT1luVjRTM0ZHTWpGQ05TOW5RV2xtVmtSWlRncFBNekZ0U2pKdllVdHNPV3gy
ZURaQ2JUVXZXV1owSzBKemFFMWFVRTFMWldOVFlqbFZUbVpOWTNKcmIzbFVWSFo1WmpjeVIzSnNT
bmNyZVhsMFdVbDFDbXcyYW01WlZHOVpaVU5vT0RSblFXeEpaR1Z4VUdnd1pIWTRlbmxpWlZKUGFr
bDZOVEpsYkRGRU9EVndkazVPWTFKemVHZEdWWElyUXpoUmNGTXdaRklLTTJzMFYwVjJaWFZaT0Zw
WWEwNURXWFY2TTB0Rk5rUTNZVlJTVjFBNFduRlNNM1UxYW1KMVNtOXdWRmRNV1VwVVFWTTFhMlpD
TVZkb2RuY3ZNelJWY1Fwc1NYSXJWSFJDWkRrMVdXVnVRMmh5ZVVwQmFVcG9NVEJzZEVSd1pFVkdi
RE50WXpGSWNubGFSaTh2UW1GbFZIVXZRVXN5Wkd4a1JqWlVUREZuY1hwV0NsVk1MMU5XU0VGMGNr
VjBXV0ZLSzNCTE4zbGhTRXRFWkhBeVNUVnBOaXRTY0VFMVFuRklZVmhvVGxkdE1VdDBMMVZQYVRS
WFlsSmtXRVY0YURsWE5uUUtZMHBGWjJaWWIxZDRlVWR3ZEZabU1VSnBWV0prWnowOUNpMHRMUzB0
UlU1RUlFTkZVbFJKUmtsRFFWUkZMUzB0TFMwSwogICAgc2VydmVyOiBodHRwczovLzM0LjI3LjE0
Ny45MgogIG5hbWU6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9w
cm9qZWN0LWNsdXN0ZXIKY29udGV4dHM6Ci0gY29udGV4dDoKICAgIGNsdXN0ZXI6IGdrZV90ZXJy
YWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9wcm9qZWN0LWNsdXN0ZXIKICAgIHVz
ZXI6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1jZW50cmFsMV9wcm9qZWN0LWNs
dXN0ZXIKICBuYW1lOiBna2VfdGVycmFmb3JtLXByb2plY3QtYXRzZXJnZTFfdXMtY2VudHJhbDFf
cHJvamVjdC1jbHVzdGVyCmN1cnJlbnQtY29udGV4dDogZ2tlX3RlcnJhZm9ybS1wcm9qZWN0LWF0
c2VyZ2UxX3VzLWNlbnRyYWwxX3Byb2plY3QtY2x1c3RlcgpraW5kOiBDb25maWcKcHJlZmVyZW5j
ZXM6IHt9CnVzZXJzOgotIG5hbWU6IGdrZV90ZXJyYWZvcm0tcHJvamVjdC1hdHNlcmdlMV91cy1j
ZW50cmFsMV9wcm9qZWN0LWNsdXN0ZXIKICB1c2VyOgogICAgZXhlYzoKICAgICAgYXBpVmVyc2lv
bjogY2xpZW50LmF1dGhlbnRpY2F0aW9uLms4cy5pby92MWJldGExCiAgICAgIGNvbW1hbmQ6IGdr
ZS1nY2xvdWQtYXV0aC1wbHVnaW4KICAgICAgaW5zdGFsbEhpbnQ6IEluc3RhbGwgZ2tlLWdjbG91
ZC1hdXRoLXBsdWdpbiBmb3IgdXNlIHdpdGgga3ViZWN0bCBieSBmb2xsb3dpbmcKICAgICAgICBo
dHRwczovL2Nsb3VkLmdvb2dsZS5jb20vYmxvZy9wcm9kdWN0cy9jb250YWluZXJzLWt1YmVybmV0
ZXMva3ViZWN0bC1hdXRoLWNoYW5nZXMtaW4tZ2tlCiAgICAgIHByb3ZpZGVDbHVzdGVySW5mbzog
dHJ1ZQo=

name: Deployment
on:
  push:
    branches: [atserge1]
  workflow_dispatch:
jobs:
  deploy-to-kubernetes:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.ATSERGE_SA_KEY }}
          project_id: ${{ secrets.ID_PROJECT }}
          export_default_credentials: true
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.9
      
      # - name: Debug secrets context
      #   run: |
      #     echo "Hello"
      #    echo ${{ secrets.KUBECONFIG }} 
      #     echo "${{ secrets }}"

      # - id: 'kubeconfig'
      #   run: 'mkdir ~/.kube && cat $KUBECONFIG > ~/.kube/config'
      - name:
        run: |
          mkdir $HOME/.kube
          echo ${{ env.KUBE_CONFIG }} | base64 --decode > $HOME/.kube/config
                
      - name: Terraform init
        run: |
          cd deployment
          terraform init

      - name: Terraform apply
        run: |
          cd deployment
          terraform apply -auto-approve