

name: Test
on:
  push:
    branches: [ Vika ]
    
  workflow_dispatch:
jobs:
  build-push-gcr:
    name: check  NS module
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Authenticate to GCP
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.SERVICE_ACCOUNT }}'

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.9
        
    - name: Terraform init
      working-directory: ./modules/Namespace/module
      run: |- 
        terraform init
      
    - name: Debug
      run: echo "$GITHUB_REF"

    - name: Terraform validate
      working-directory: ./modules/Namespace/module
      run: |- 
        terraform validate
        
    - name: Terraform apply
      working-directory: ./modules/Namespace/module
      run: |- 
        terraform apply -auto-approve  
